AWSTemplateFormatVersion: '2010-09-09'
Description: Cf template for order service container
Resources:
  MyTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: arn:aws:iam::862999377122:role/ecsTaskExecutionRole
      Cpu: 256
      Memory: 512
      NetworkMode: awsvpc
      ContainerDefinitions:
        - Name: ordersdemo
          Image: 862999377122.dkr.ecr.ap-south-1.amazonaws.com/ordersdemo:v1
          MemoryReservation: 256
          Memory: 512
          PortMappings:
            - ContainerPort: 8080
              Protocol: tcp
  ECSCluster:
    Type: 'AWS::ECS::Cluster'
    Properties:
      ClusterName: MyFargateCluster